add forgejo cli fj

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.3.5 (https://bashly.dev)
+# This script was generated by bashly 1.3.8 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -70,6 +70,7 @@ gup_install_usage() {
 	echo
 	printf "%s\n" "Development Commands:"
 	printf "  %s   github cli\n" "githubcli        "
+	printf "  %s   forgejo cli\n" "forgejocli       "
 	printf "  %s   A simple terminal UI for git commands\n" "lazygit          "
 	printf "  %s   mkcert is a simple tool for making locally-trusted development certificates\n" "mkcert           "
 	printf "  %s   Sloc Cloc and Code (scc)\n" "scc              "
@@ -318,6 +319,28 @@ gup_install_githubcli_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install githubcli\n"
 	printf "  gup install githubcli --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n "$long_usage" ]]; then
+		# :command.usage_options
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_forgejocli_usage() {
+	printf "gup install forgejocli - forgejo cli\n\n"
+
+	printf "%s\n" "Usage:"
+	printf "  gup install forgejocli\n"
+	printf "  gup install forgejocli --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -1960,6 +1983,33 @@ gup_install_githubcli_command() {
 					download "${vers}"
 			fi
 	fi
+}
+
+# :command.function
+gup_install_forgejocli_command() {
+
+	# src/install_forgejocli_command.sh
+	APP="fj"
+	DL="https://codeberg.org/forgejo-contrib/forgejo-cli/releases/download/latest/forgejo-cli-linux.tar.gz"
+	FN="forgejo-cli-linux.tar.gz"
+
+	BDIR=/usr/local/bin
+
+	function download() {
+			echo "download $1 version"
+			echo "installing ${vers}"
+			sudo rm -f /tmp/"${FN}"
+			sudo rm -f /tmp/"${APP}"
+			wget -qc "${DL}" -O /tmp/"${FN}"
+			sudo tar -axf /tmp/"${FN}" -C /tmp
+			ls -l /tmp
+			sudo rm -rf "${BDIR}/${APP}"
+			sudo install -Dm755 /tmp/"${APP}" "${BDIR}/${APP}"
+			sudo rm -f /tmp/"${FN}"
+			sudo rm -f /tmp/"${APP}"
+	}
+
+	download new
 }
 
 # :command.function
@@ -3719,6 +3769,13 @@ gup_install_parse_requirements() {
 			shift $#
 			;;
 
+		forgejocli)
+			action="forgejocli"
+			shift
+			gup_install_forgejocli_parse_requirements "$@"
+			shift $#
+			;;
+
 		lazygit)
 			action="lazygit"
 			shift
@@ -4476,6 +4533,53 @@ gup_install_githubcli_parse_requirements() {
 
 	# :command.command_filter
 	action="install githubcli"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
+gup_install_forgejocli_parse_requirements() {
+	local key
+
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+			--help | -h)
+				long_usage=yes
+				gup_install_forgejocli_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install forgejocli"
 
 	# :command.parse_requirements_while
 	while [[ $# -gt 0 ]]; do
@@ -7448,6 +7552,7 @@ run() {
 		"install doctl") gup_install_doctl_command ;;
 		"install terraform") gup_install_terraform_command ;;
 		"install githubcli") gup_install_githubcli_command ;;
+		"install forgejocli") gup_install_forgejocli_command ;;
 		"install lazygit") gup_install_lazygit_command ;;
 		"install mkcert") gup_install_mkcert_command ;;
 		"install scc") gup_install_scc_command ;;
