add yamlfmt

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -78,6 +78,7 @@ gup_install_usage() {
 	printf "  %s   Generate type-safe code from SQL\n" "sqlc             "
 	printf "  %s   Ultimate Packer for eXecutables\n" "upx              "
 	printf "  %s   tailwindcss cli\n" "tailwindcss      "
+	printf "  %s   an extensible command line tool or library to format yaml files.\n" "yamlfmt          "
 	echo
 	printf "%s\n" "Go Development Commands:"
 	printf "  %s   go programming language\n" "go               "
@@ -503,6 +504,28 @@ gup_install_tailwindcss_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install tailwindcss\n"
 	printf "  gup install tailwindcss --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n "$long_usage" ]]; then
+		# :command.usage_options
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_yamlfmt_usage() {
+	printf "gup install yamlfmt - an extensible command line tool or library to format yaml files.\n\n"
+
+	printf "%s\n" "Usage:"
+	printf "  gup install yamlfmt\n"
+	printf "  gup install yamlfmt --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -2364,6 +2387,13 @@ gup_install_tailwindcss_command() {
 }
 
 # :command.function
+gup_install_yamlfmt_command() {
+
+	# src/install_yamlfmt_command.sh
+	go install github.com/google/yamlfmt/cmd/yamlfmt@latest
+}
+
+# :command.function
 gup_install_go_command() {
 
 	# src/install_go_command.sh
@@ -4075,6 +4105,13 @@ gup_install_parse_requirements() {
 			shift $#
 			;;
 
+		yamlfmt)
+			action="yamlfmt"
+			shift
+			gup_install_yamlfmt_parse_requirements "$@"
+			shift $#
+			;;
+
 		go)
 			action="go"
 			shift
@@ -5215,6 +5252,53 @@ gup_install_tailwindcss_parse_requirements() {
 
 	# :command.command_filter
 	action="install tailwindcss"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
+gup_install_yamlfmt_parse_requirements() {
+	local key
+
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+			--help | -h)
+				long_usage=yes
+				gup_install_yamlfmt_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install yamlfmt"
 
 	# :command.parse_requirements_while
 	while [[ $# -gt 0 ]]; do
@@ -8242,6 +8326,7 @@ run() {
 		"install sqlc") gup_install_sqlc_command ;;
 		"install upx") gup_install_upx_command ;;
 		"install tailwindcss") gup_install_tailwindcss_command ;;
+		"install yamlfmt") gup_install_yamlfmt_command ;;
 		"install go") gup_install_go_command ;;
 		"install tinygo") gup_install_tinygo_command ;;
 		"install godevenv") gup_install_godevenv_command ;;
