add bun

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -59,6 +59,7 @@ gup_install_usage() {
 	printf "  %s   install gup command\n" "gup              "
 	printf "  %s   nerdfonts installer\n" "nerdfonts        "
 	printf "  %s   update script for apt update\n" "update           "
+	printf "  %s   deno js engine\n" "deno             "
 	echo
 	printf "%s\n" "Development Commands:"
 	printf "  %s   Live reload for Go apps\n" "air              "
@@ -110,7 +111,7 @@ gup_install_usage() {
 	printf "%s\n" "Language Commands:"
 	printf "  %s   go programming language\n" "go               "
 	printf "  %s   nodejs js engine\n" "nodejs           "
-	printf "  %s   deno js engine\n" "deno             "
+	printf "  %s   bun js engine\n" "bun              "
 	printf "  %s   zig programming language\n" "zig              "
 	printf "  %s   zig language server\n" "zls              "
 	echo
@@ -1103,6 +1104,27 @@ gup_install_deno_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install deno\n"
 	printf "  gup install deno --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n "$long_usage" ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_bun_usage() {
+	printf "gup install bun - bun js engine\n\n"
+
+	printf "%s\n" "Usage:"
+	printf "  gup install bun\n"
+	printf "  gup install bun --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -2598,6 +2620,86 @@ gup_install_deno_command() {
 }
 
 # :command.function
+gup_install_bun_command() {
+
+	# src/install_bun_command.sh
+	APP="bun"
+	REPO="https://github.com/oven-sh/bun"
+	vers=$(git ls-remote --tags ${REPO} | grep "refs/tags/bun-.*[0-9]$" | grep -v -e "build" -e "alpha" -e "beta" | awk '{print $2}' | sed 's/refs\/tags\///g' | sort -V | uniq | tail -1)
+
+	if [ $(id -u) == 0 ]; then
+		BDIR="/usr/local/bin"
+	else
+		BDIR="${HOME}/.bun/bin"
+	fi
+
+	platform=$(uname -ms)
+	target=""
+	case $platform in
+	'Darwin x86_64')
+			target=darwin-x64
+			;;
+	'Darwin arm64')
+			target=darwin-aarch64
+			;;
+	'Linux aarch64' | 'Linux arm64')
+			target=linux-aarch64
+			;;
+	'MINGW64'*)
+			target=windows-x64
+			;;
+	'Linux x86_64' | *)
+			target=linux-x64
+			;;
+	esac
+
+	# If AVX2 isn't supported, use the -baseline build
+	case "$target" in
+	'darwin-x64'*)
+			if [[ $(sysctl -a | grep machdep.cpu | grep AVX2) == '' ]]; then
+					target="$target-baseline"
+			fi
+			;;
+	'linux-x64'*)
+			# If AVX2 isn't supported, use the -baseline build
+			if [[ $(cat /proc/cpuinfo | grep avx2) = '' ]]; then
+					target="$target-baseline"
+			fi
+			;;
+	esac
+
+	setup() {
+		mkdir -p ${BDIR}
+		grep "export BUN_INSTALL" ${HOME}/.bashrc > /dev/null || echo "export BUN_INSTALL=${BDIR}" >> ${HOME}/.bashrc
+		grep "export PATH=\$BUN_INSTALL/bin:\$PATH" ~/.bashrc > /dev/null || echo "export PATH=\$BUN_INSTALL/bin:\$PATH" >> ${HOME}/.bashrc
+	}
+
+	download() {
+		echo "download $1 version"
+		echo "installing ${vers}"
+		setup
+		FN=${APP}-${target}.zip
+		rm -rf /tmp/${APP}-${target}
+		rm -f /tmp/${FN}
+		wget -qc ${REPO}/releases/download/${vers}/${FN} -O /tmp/${FN}
+		unzip /tmp/${FN} -d /tmp/${APP}-${target}
+		install /tmp/${APP}-${target}/${APP}-${target}/${APP} ${BDIR}/${APP}
+		rm -rf /tmp/${APP}-${target}
+		rm -f /tmp/${FN}
+	}
+
+	if [ -z $(which ${APP}) ]; then
+		download new
+	else
+		APPBIN=$(which ${APP})
+		APPVER=$(${APPBIN} --version)
+		GITVER=$(echo $vers | sed 's/^bun-v//')
+		[ "${APPVER}" = "${GITVER}" ] && echo "${APP} version is current" || download ${vers}
+	fi
+
+}
+
+# :command.function
 gup_install_zig_command() {
 
 	# src/install_zig_command.sh
@@ -3182,6 +3284,13 @@ gup_install_parse_requirements() {
 			action="deno"
 			shift
 			gup_install_deno_parse_requirements "$@"
+			shift $#
+			;;
+
+		bun)
+			action="bun"
+			shift
+			gup_install_bun_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -5337,6 +5446,51 @@ gup_install_deno_parse_requirements() {
 }
 
 # :command.parse_requirements
+gup_install_bun_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+			--help | -h)
+				long_usage=yes
+				gup_install_bun_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install bun"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
 gup_install_zig_parse_requirements() {
 	# :command.fixed_flags_filter
 	while [[ $# -gt 0 ]]; do
@@ -5867,6 +6021,7 @@ run() {
 		"install wkhtmltopdf") gup_install_wkhtmltopdf_command ;;
 		"install nodejs") gup_install_nodejs_command ;;
 		"install deno") gup_install_deno_command ;;
+		"install bun") gup_install_bun_command ;;
 		"install zig") gup_install_zig_command ;;
 		"install zls") gup_install_zls_command ;;
 		"install zfsnap") gup_install_zfsnap_command ;;
