add: add k9s lazygit

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -106,6 +106,7 @@ gup_install_usage() {
 	echo
 	printf "%s\n" "Utilities Commands:"
 	printf "  %s   gotop terminal based graphical activity monitor\n" "gotop            "
+	printf "  %s   A simple terminal UI for git commands\n" "lazygit          "
 	printf "  %s   pgcat postgresql pooler\n" "pgcat            "
 	printf "  %s   A portable, performant script to make rolling ZFS snapshots easy\n" "zfsnap           "
 	echo
@@ -471,6 +472,35 @@ gup_install_kubectl_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install kubectl\n"
 	printf "  gup install kubectl --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_lazygit_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "gup install lazygit - A simple terminal UI for git commands\n"
+		echo
+
+	else
+		printf "gup install lazygit - A simple terminal UI for git commands\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  gup install lazygit\n"
+	printf "  gup install lazygit --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -1580,17 +1610,17 @@ gup_install_k9s_command() {
 			mkdir -p ${IDIR}
 			FN=k9s_Linux_amd64.tar.gz
 			rm -rf /tmp/k9s /tmp/${FN}
-			echo wget -qc ${REPO}/releases/download/${vers}/${FN} -O /tmp/${FN}
-			tar axf ${FN} /tmp/k9s
-			install /tmp/k9s $IDIR
-			rm -rf /tmp/k9s /tmp/${FN}
+			wget -qc ${REPO}/releases/download/${vers}/${FN} -O /tmp/${FN}
+			tar axf /tmp/${FN} k9s
+			install k9s $IDIR
+			rm -rf k9s /tmp/${FN}
 	}
 
 	if [ -z $(which ${APP}) ]; then
 			download new
 	else
 		APPBIN=$(which ${APP})
-		APPVER=$(${APPBIN} version | grep -e "^Version" | awk '{print $2}')
+		APPVER=$(${APPBIN} version 2>&1 | grep Version | awk '{print $2}')
 		[ "${APPVER}" = "${vers}" ] && echo "${APP} version is current" || download ${vers}
 	fi
 
@@ -1602,6 +1632,41 @@ gup_install_kubectl_command() {
 	curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
 	sudo install kubectl /usr/local/bin
 	rm kubectl
+
+}
+
+# :command.function
+gup_install_lazygit_command() {
+	# src/install_lazygit_command.sh
+	APP="lazygit"
+	REPO="https://github.com/jesseduffield/lazygit"
+	vers=$(git ls-remote --tags ${REPO} | grep "refs/tags.*[0-9]$" | awk '{print $2}' | sed 's/refs\/tags\///' | sort -V | uniq | tail -1 | sed 's/^v//')
+
+	IDIR="${HOME}/.local/bin"
+
+	if [ $(id -u) == 0 ]; then
+		IDIR="/usr/local/bin"
+	fi
+
+	function download() {
+			echo "download $1 version"
+			echo "installing ${vers}"
+			mkdir -p ${IDIR}
+			FN=lazygit_${vers}_Linux_x86_64.tar.gz
+			rm -rf /tmp/lazygit /tmp/${FN}
+			wget -qc ${REPO}/releases/download/v${vers}/${FN} -O /tmp/${FN}
+			tar axf /tmp/${FN} lazygit
+			install lazygit $IDIR
+			rm -rf lazygit /tmp/${FN}
+	}
+
+	if [ -z $(which ${APP}) ]; then
+			download new
+	else
+		APPBIN=$(which ${APP})
+		APPVER=$(${APPBIN} --version | awk '{print $6}' | sed 's/,//g' | awk -F'=' '{print $2}')
+		[ "${APPVER}" = "${vers}" ] && echo "${APP} version is current" || download ${vers}
+	fi
 
 }
 
@@ -2426,6 +2491,13 @@ gup_install_parse_requirements() {
 			shift $#
 			;;
 
+		lazygit)
+			action="lazygit"
+			shift
+			gup_install_lazygit_parse_requirements "$@"
+			shift $#
+			;;
+
 		loki)
 			action="loki"
 			shift
@@ -3092,6 +3164,50 @@ gup_install_kubectl_parse_requirements() {
 
 	# :command.command_filter
 	action="install kubectl"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
+gup_install_lazygit_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				gup_install_lazygit_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install lazygit"
 
 	# :command.parse_requirements_while
 	while [[ $# -gt 0 ]]; do
@@ -4284,6 +4400,7 @@ run() {
 		"install hugo") gup_install_hugo_command ;;
 		"install k9s") gup_install_k9s_command ;;
 		"install kubectl") gup_install_kubectl_command ;;
+		"install lazygit") gup_install_lazygit_command ;;
 		"install loki") gup_install_loki_command ;;
 		"install litexl") gup_install_litexl_command ;;
 		"install minikube") gup_install_minikube_command ;;
