add tailwindcss cli

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -89,6 +89,7 @@ gup_install_usage() {
 	printf "  %s   caddy2 web server\n" "caddy2           "
 	printf "  %s   hugo website generator\n" "hugo             "
 	printf "  %s   traefik\n" "traefik          "
+	printf "  %s   tailwindcss cli\n" "tailwindcss      "
 	echo
 	printf "%s\n" "Kubernetes Commands:"
 	printf "  %s   consul\n" "consul           "
@@ -916,6 +917,35 @@ gup_install_traefik_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install traefik\n"
 	printf "  gup install traefik --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_tailwindcss_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "gup install tailwindcss - tailwindcss cli\n"
+		echo
+
+	else
+		printf "gup install tailwindcss - tailwindcss cli\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  gup install tailwindcss\n"
+	printf "  gup install tailwindcss --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -2179,6 +2209,36 @@ gup_install_traefik_command() {
 }
 
 # :command.function
+gup_install_tailwindcss_command() {
+	# src/install_tailwindcss_command.sh
+	APP="tailwindcss"
+	REPO="https://github.com/tailwindlabs/tailwindcss"
+	vers=$(git ls-remote --tags ${REPO} | grep "refs/tags.*[0-9]$" | awk '{print $2}' | sed 's/refs\/tags\///' | sort -V | uniq | tail -1)
+
+	if [ $(id -u) == 0 ]; then
+		BDIR="/usr/local/bin"
+	else
+		BDIR="${HOME}/.local/bin"
+	fi
+
+	function download() {
+			echo "download $1 version"
+			echo "installing ${vers}"
+			FN=${APP}-linux-x64
+			wget -qc ${REPO}/releases/download/${vers}/${FN} -O ${BDIR}/${APP}
+			chmod +x ${BDIR}/${APP}
+	}
+
+	if [ -z $(which ${APP}) ]; then
+			download new
+	else
+			APPBIN=$(which ${APP})
+			APPVER=$(${APPBIN} --help 2>&1 | grep ^${APP} | awk '{print $2}')
+			[ "${APPVER}" = "${vers}" ] && echo "${APP} version is current" || download ${vers}
+	fi
+}
+
+# :command.function
 gup_install_update_command() {
 	# src/install_update_command.sh
 	cat <<-_EOF_ | sudo tee /usr/local/bin/update > /dev/null
@@ -2605,6 +2665,13 @@ gup_install_parse_requirements() {
 			action="traefik"
 			shift
 			gup_install_traefik_parse_requirements "$@"
+			shift $#
+			;;
+
+		tailwindcss)
+			action="tailwindcss"
+			shift
+			gup_install_tailwindcss_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -3882,6 +3949,50 @@ gup_install_traefik_parse_requirements() {
 }
 
 # :command.parse_requirements
+gup_install_tailwindcss_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				gup_install_tailwindcss_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install tailwindcss"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
 gup_install_update_parse_requirements() {
 	# :command.fixed_flags_filter
 	while [[ $# -gt 0 ]]; do
@@ -4428,6 +4539,7 @@ run() {
 		"install promtail") gup_install_promtail_command ;;
 		"install snmp_exporter") gup_install_snmp_exporter_command ;;
 		"install traefik") gup_install_traefik_command ;;
+		"install tailwindcss") gup_install_tailwindcss_command ;;
 		"install update") gup_install_update_command ;;
 		"install vagrant") gup_install_vagrant_command ;;
 		"install wkhtmltopdf") gup_install_wkhtmltopdf_command ;;
