add ziglang

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.1.6 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.1.10 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -99,11 +99,12 @@ gup_install_usage() {
 	echo
 	printf "%s\n" "Containers Commands:"
 	printf "  %s   docker-compose\n" "docker-compose   "
-	printf "  %s   podman container system\n" "podman           "
+	printf "  %s   podman container\n" "podman           "
 	printf "  %s   HashiCorp Vagrant\n" "vagrant          "
 	echo
 	printf "%s\n" "Language Commands:"
 	printf "  %s   go programming language\n" "go               "
+	printf "  %s   zig programming language\n" "zig              "
 	echo
 	printf "%s\n" "Utilities Commands:"
 	printf "  %s   gotop terminal based graphical activity monitor\n" "gotop            "
@@ -760,11 +761,11 @@ gup_install_pgcat_usage() {
 # :command.usage
 gup_install_podman_usage() {
 	if [[ -n $long_usage ]]; then
-		printf "gup install podman - podman container system\n"
+		printf "gup install podman - podman container\n"
 		echo
 
 	else
-		printf "gup install podman - podman container system\n"
+		printf "gup install podman - podman container\n"
 		echo
 
 	fi
@@ -1048,6 +1049,35 @@ gup_install_wkhtmltopdf_usage() {
 }
 
 # :command.usage
+gup_install_zig_usage() {
+	if [[ -n $long_usage ]]; then
+		printf "gup install zig - zig programming language\n"
+		echo
+
+	else
+		printf "gup install zig - zig programming language\n"
+		echo
+
+	fi
+
+	printf "%s\n" "Usage:"
+	printf "  gup install zig\n"
+	printf "  gup install zig --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n $long_usage ]]; then
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
 gup_install_zfsnap_usage() {
 	if [[ -n $long_usage ]]; then
 		printf "gup install zfsnap - A portable, performant script to make rolling ZFS snapshots easy\n"
@@ -1271,12 +1301,16 @@ gup_systemd_promtail_usage() {
 }
 
 # :command.normalize_input
+# :command.normalize_input_function
 normalize_input() {
-	local arg flags
+	local arg flags passthru
+	passthru=false
 
 	while [[ $# -gt 0 ]]; do
 		arg="$1"
-		if [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
+		if [[ $passthru == true ]]; then
+			input+=("$arg")
+		elif [[ $arg =~ ^(--[a-zA-Z0-9_\-]+)=(.+)$ ]]; then
 			input+=("${BASH_REMATCH[1]}")
 			input+=("${BASH_REMATCH[2]}")
 		elif [[ $arg =~ ^(-[a-zA-Z0-9])=(.+)$ ]]; then
@@ -1287,6 +1321,9 @@ normalize_input() {
 			for ((i = 0; i < ${#flags}; i++)); do
 				input+=("-${flags:i:1}")
 			done
+		elif [[ "$arg" == "--" ]]; then
+			passthru=true
+			input+=("$arg")
 		else
 			input+=("$arg")
 		fi
@@ -1294,6 +1331,7 @@ normalize_input() {
 		shift
 	done
 }
+
 # :command.inspect_args
 inspect_args() {
 	if ((${#args[@]})); then
@@ -1741,51 +1779,51 @@ gup_install_loki_command() {
 	config() {
 		sudo mkdir /etc/loki
 	cat <<-_EOF_ | sudo tee /etc/loki/loki-config.yml > /dev/null
-	auth_enabled: false
-	server:
-		http_listen_port: 3100
-	ingester:
-		lifecycler:
-			address: 127.0.0.1
-			ring:
-				kvstore:
-					store: inmemory
-				replication_factor: 1
-			final_sleep: 0s
-		chunk_idle_period: 5m
-		chunk_retain_period: 30s
-	schema_config:
-		configs:
-		- from: 2020-05-15
-			store: boltdb
-			object_store: filesystem
-			schema: v11
-			index:
-				prefix: index_
-				period: 168h
-	storage_config:
-		boltdb:
-			directory: /tmp/loki/index
-		filesystem:
-			directory: /tmp/loki/chunks
-	limits_config:
-		enforce_metric_name: false
-		reject_old_samples: true
-		reject_old_samples_max_age: 168h
-		max_entries_limit_per_query: 500000
-	# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
-	# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
-	#
-	# Statistics help us better understand how Loki is used, and they show us performance
-	# levels for most users. This helps us prioritize features and documentation.
-	# For more information on what's sent, look at
-	# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
-	# Refer to the buildReport method to see what goes into a report.
-	#
-	# If you would like to disable reporting, uncomment the following lines:
-	#analytics:
-	#  reporting_enabled: false
-	_EOF_
+auth_enabled: false
+server:
+	http_listen_port: 3100
+ingester:
+	lifecycler:
+		address: 127.0.0.1
+		ring:
+			kvstore:
+				store: inmemory
+			replication_factor: 1
+		final_sleep: 0s
+	chunk_idle_period: 5m
+	chunk_retain_period: 30s
+schema_config:
+	configs:
+	- from: 2020-05-15
+		store: boltdb
+		object_store: filesystem
+		schema: v11
+		index:
+			prefix: index_
+			period: 168h
+storage_config:
+	boltdb:
+		directory: /tmp/loki/index
+	filesystem:
+		directory: /tmp/loki/chunks
+limits_config:
+	enforce_metric_name: false
+	reject_old_samples: true
+	reject_old_samples_max_age: 168h
+	max_entries_limit_per_query: 500000
+# By default, Loki will send anonymous, but uniquely-identifiable usage and configuration
+# analytics to Grafana Labs. These statistics are sent to https://stats.grafana.org/
+#
+# Statistics help us better understand how Loki is used, and they show us performance
+# levels for most users. This helps us prioritize features and documentation.
+# For more information on what's sent, look at
+# https://github.com/grafana/loki/blob/main/pkg/usagestats/stats.go
+# Refer to the buildReport method to see what goes into a report.
+#
+# If you would like to disable reporting, uncomment the following lines:
+#analytics:
+#  reporting_enabled: false
+_EOF_
 	}
 
 	# download new
@@ -2097,33 +2135,33 @@ gup_install_promtail_command() {
 	config() {
 		sudo mkdir /etc/promtail
 	cat <<-_EOF_ | sudo tee /etc/promtail/promtail-config.yml > /dev/null
-	server:
-		http_listen_port: 9080
-		grpc_listen_port: 0
-	positions:
-		filename: /tmp/positions.yaml
-	clients:
-		- url: http://localhost:3100/loki/api/v1/push
-	scrape_configs:
-		- job_name: syslog
-			syslog:
-				listen_address: 0.0.0.0:1514
-				labels:
-					job: syslog
-			relabel_configs:
-				- source_labels: [__syslog_message_hostname]
-					target_label: host
-				- source_labels: [__syslog_message_hostname]
-					target_label: hostname
-				- source_labels: [__syslog_message_severity]
-					target_label: level
-				- source_labels: [__syslog_message_app_name]
-					target_label: application
-				- source_labels: [__syslog_message_facility]
-					target_label: facility
-				- source_labels: [__syslog_connection_hostname]
-					target_label: connection_hostname
-	_EOF_
+server:
+	http_listen_port: 9080
+	grpc_listen_port: 0
+positions:
+	filename: /tmp/positions.yaml
+clients:
+	- url: http://localhost:3100/loki/api/v1/push
+scrape_configs:
+	- job_name: syslog
+		syslog:
+			listen_address: 0.0.0.0:1514
+			labels:
+				job: syslog
+		relabel_configs:
+			- source_labels: [__syslog_message_hostname]
+				target_label: host
+			- source_labels: [__syslog_message_hostname]
+				target_label: hostname
+			- source_labels: [__syslog_message_severity]
+				target_label: level
+			- source_labels: [__syslog_message_app_name]
+				target_label: application
+			- source_labels: [__syslog_message_facility]
+				target_label: facility
+			- source_labels: [__syslog_connection_hostname]
+				target_label: connection_hostname
+_EOF_
 	}
 
 	# download new
@@ -2242,9 +2280,9 @@ gup_install_tailwindcss_command() {
 gup_install_update_command() {
 	# src/install_update_command.sh
 	cat <<-_EOF_ | sudo tee /usr/local/bin/update > /dev/null
-	#!/bin/bash
-	sudo bash -c "apt update -y && apt full-upgrade -y && apt autoremove -y && apt autoclean -y"
-	_EOF_
+#!/bin/bash
+sudo bash -c "apt update -y && apt full-upgrade -y && apt autoremove -y && apt autoclean -y"
+_EOF_
 
 	sudo chmod +x /usr/local/bin/update
 }
@@ -2290,6 +2328,41 @@ gup_install_wkhtmltopdf_command() {
 }
 
 # :command.function
+gup_install_zig_command() {
+	# src/install_zig_command.sh
+	APP="zig"
+	REPO="https://github.com/ziglang/zig"
+	DLREPO="https://ziglang.org/download"
+	vers=$(git ls-remote --tags ${REPO} | grep "refs/tags/.*[0-9]$" | grep -v -e rc -e alpha -e beta | awk '{print $2}' | sed 's/refs\/tags\///' | sort -V | uniq | tail -1)
+
+	IDIR=/usr/local/lib
+	BDIR=/usr/local/bin
+
+	function download(){
+			echo "download $1 version"
+			echo "installing $vers"
+			FN=zig-linux-x86_64-$vers.tar.xz
+			rm -f /tmp/${FN}
+			wget -qc ${DLREPO}/$vers/${FN} -O /tmp/${FN}
+			sudo rm -f ${BDIR}/zig
+			sudo rm -rf ${IDIR}/zig
+			sudo mkdir -p ${IDIR}/zig
+			sudo tar axf /tmp/${FN} --strip-components=1 -C ${IDIR}/zig
+			sudo ln -sf ${IDIR}/zig/zig ${BDIR}/zig
+			rm -f /tmp/${FN}
+	}
+
+	if [ -z $(which ${APP}) ]; then
+			download new
+	else
+			APPBIN=$(which ${APP})
+			APPVER=$(${APPBIN} version)
+			[ "${APPVER}" = "${vers}" ] && echo "${APP} version is current" || download ${vers}
+	fi
+
+}
+
+# :command.function
 gup_install_zfsnap_command() {
 	# src/install_zfsnap_command.sh
 	APP="zfsnap"
@@ -2328,18 +2401,18 @@ gup_systemd_loki_command() {
 	# src/systemd_loki_command.sh
 	function servicefile() {
 	cat <<-_EOF_ | sudo tee /etc/systemd/system/loki.service > /dev/null
-	[Unit]
-	Description=Loki service
-	After=network.target
+[Unit]
+Description=Loki service
+After=network.target
 
-	[Service]
-	Type=simple
-	User=root
-	ExecStart=/usr/local/bin/loki -config.file /etc/loki/loki-config.yml
+[Service]
+Type=simple
+User=root
+ExecStart=/usr/local/bin/loki -config.file /etc/loki/loki-config.yml
 
-	[Install]
-	WantedBy=multi-user.target
-	_EOF_
+[Install]
+WantedBy=multi-user.target
+_EOF_
 	}
 
 	servicefile
@@ -2351,18 +2424,18 @@ gup_systemd_promtail_command() {
 	# src/systemd_promtail_command.sh
 	function servicefile() {
 	cat <<-_EOF_ | sudo tee /etc/systemd/system/promtail.service > /dev/null
-	[Unit]
-	Description=Promtail service
-	After=network.target
+[Unit]
+Description=Promtail service
+After=network.target
 
-	[Service]
-	Type=simple
-	User=root
-	ExecStart=/usr/local/bin/promtail -config.file /etc/promtail/promtail-config.yml
+[Service]
+Type=simple
+User=root
+ExecStart=/usr/local/bin/promtail -config.file /etc/promtail/promtail-config.yml
 
-	[Install]
-	WantedBy=multi-user.target
-	_EOF_
+[Install]
+WantedBy=multi-user.target
+_EOF_
 	}
 
 	servicefile
@@ -2693,6 +2766,13 @@ gup_install_parse_requirements() {
 			action="wkhtmltopdf"
 			shift
 			gup_install_wkhtmltopdf_parse_requirements "$@"
+			shift $#
+			;;
+
+		zig)
+			action="zig"
+			shift
+			gup_install_zig_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -3521,14 +3601,15 @@ gup_install_nerdfonts_parse_requirements() {
 			*)
 				# :command.parse_requirements_case
 				# :command.parse_requirements_case_repeatable
-
+				# :argument.case_repeatable
+				escaped="$(printf '%q' "$1")"
 				if [[ -z ${args['font']+x} ]]; then
-					args['font']="\"$1\""
-					shift
+					args['font']="$escaped"
 				else
-					args['font']="${args[font]} \"$1\""
-					shift
+					args['font']="${args['font']} $escaped"
+
 				fi
+				shift
 
 				;;
 
@@ -4125,6 +4206,50 @@ gup_install_wkhtmltopdf_parse_requirements() {
 }
 
 # :command.parse_requirements
+gup_install_zig_parse_requirements() {
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		case "${1:-}" in
+			--help | -h)
+				long_usage=yes
+				gup_install_zig_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install zig"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
 gup_install_zfsnap_parse_requirements() {
 	# :command.fixed_flags_filter
 	while [[ $# -gt 0 ]]; do
@@ -4543,6 +4668,7 @@ run() {
 		"install update") gup_install_update_command ;;
 		"install vagrant") gup_install_vagrant_command ;;
 		"install wkhtmltopdf") gup_install_wkhtmltopdf_command ;;
+		"install zig") gup_install_zig_command ;;
 		"install zfsnap") gup_install_zfsnap_command ;;
 		"remove") gup_remove_command ;;
 		"remove consul") gup_remove_consul_command ;;
