add goose database migration

diff --git a/gup b/gup
--- a/gup
+++ b/gup
@@ -155,6 +155,7 @@ gup_install_usage() {
 	printf "  %s   Ultimate Packer for eXecutables\n" "upx              "
 	echo
 	printf "%s\n" "Database & Code Generation Commands:"
+	printf "  %s   Database migration tool for Go\n" "goose            "
 	printf "  %s   Generate type-safe code from SQL\n" "sqlc             "
 	echo
 	printf "%s\n" "Security & Vulnerability Scanning Commands:"
@@ -1752,6 +1753,28 @@ gup_install_upx_usage() {
 	printf "%s\n" "Usage:"
 	printf "  gup install upx\n"
 	printf "  gup install upx --help | -h\n"
+	echo
+
+	# :command.long_usage
+	if [[ -n "$long_usage" ]]; then
+		# :command.usage_options
+		printf "%s\n" "Options:"
+
+		# :command.usage_fixed_flags
+		printf "  %s\n" "--help, -h"
+		printf "    Show this help\n"
+		echo
+
+	fi
+}
+
+# :command.usage
+gup_install_goose_usage() {
+	printf "gup install goose - Database migration tool for Go\n\n"
+
+	printf "%s\n" "Usage:"
+	printf "  gup install goose\n"
+	printf "  gup install goose --help | -h\n"
 	echo
 
 	# :command.long_usage
@@ -4272,6 +4295,21 @@ gup_install_upx_command() {
 }
 
 # :command.function
+gup_install_goose_command() {
+
+	# src/install_goose_command.sh
+	set -euo pipefail
+
+	APP="goose"
+	REPO="pressly/goose"
+	vers=$(gup_get_latest_release "${REPO}")
+
+	gup_ensure_go
+	go install github.com/pressly/goose/v3/cmd/goose@"${vers}"
+
+}
+
+# :command.function
 gup_install_sqlc_command() {
 
 	# src/install_sqlc_command.sh
@@ -5043,6 +5081,13 @@ gup_install_parse_requirements() {
 			action="upx"
 			shift
 			gup_install_upx_parse_requirements "$@"
+			shift $#
+			;;
+
+		goose)
+			action="goose"
+			shift
+			gup_install_goose_parse_requirements "$@"
 			shift $#
 			;;
 
@@ -8495,6 +8540,53 @@ gup_install_upx_parse_requirements() {
 }
 
 # :command.parse_requirements
+gup_install_goose_parse_requirements() {
+	local key
+
+	# :command.fixed_flags_filter
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+			--help | -h)
+				long_usage=yes
+				gup_install_goose_usage
+				exit
+				;;
+
+			*)
+				break
+				;;
+
+		esac
+	done
+
+	# :command.command_filter
+	action="install goose"
+
+	# :command.parse_requirements_while
+	while [[ $# -gt 0 ]]; do
+		key="$1"
+		case "$key" in
+
+			-?*)
+				printf "invalid option: %s\n" "$key" >&2
+				exit 1
+				;;
+
+			*)
+				# :command.parse_requirements_case
+				# :command.parse_requirements_case_simple
+				printf "invalid argument: %s\n" "$key" >&2
+				exit 1
+
+				;;
+
+		esac
+	done
+
+}
+
+# :command.parse_requirements
 gup_install_sqlc_parse_requirements() {
 	local key
 
@@ -9108,6 +9200,7 @@ run() {
 		"install terraform") gup_install_terraform_command ;;
 		"install distrobuilder") gup_install_distrobuilder_command ;;
 		"install upx") gup_install_upx_command ;;
+		"install goose") gup_install_goose_command ;;
 		"install sqlc") gup_install_sqlc_command ;;
 		"install mkcert") gup_install_mkcert_command ;;
 		"install govulncheck") gup_install_govulncheck_command ;;
